import type {
  Discount,
  EventItem,
  Product,
  Review,
  Service,
  SiteSettings,
} from "./types";

export const defaultSettings: SiteSettings = {
  brand: {
    name: "U.S.A. Motorcycle Centre",
    legalName: "U.S.A. Motorcycle Centre Pty Ltd",
    shortName: "U.S.A. MCC",
    tagline: "Harley® specialist repair, parts and rider gear — Illawarra since 1992.",
    slogan: "U.S.A. Motorcycle Centre is the name. Servicing Harleys is our game.",
    established: 1992,
    logo: "/brand/logo.png",
    logoInvert: false,
  },
  colors: {
    accent: "#FF6A00",
    accentSoft: "#FF8A3D",
    ink: "#0B0B0C",
  },
  contact: {
    phone: "(02) 4257 2333",
    phoneHref: "tel:+61242572333",
    email: "workshop@usamotorcyclecentre.com.au",
    addressLine: "8 Miall Way",
    suburb: "Albion Park Rail",
    state: "NSW",
    postcode: "2527",
    country: "Australia",
    mapsUrl:
      "https://www.google.com/maps/search/?api=1&query=8+Miall+Way+Albion+Park+Rail+NSW+2527",
    abn: "",
  },
  hours: {
    monday: { open: "08:00", close: "17:00", closed: false },
    tuesday: { open: "08:00", close: "17:00", closed: false },
    wednesday: { open: "08:00", close: "17:00", closed: false },
    thursday: { open: "08:00", close: "17:00", closed: false },
    friday: { open: "08:00", close: "17:00", closed: false },
    saturday: { open: "08:00", close: "12:00", closed: false },
    sunday: { open: "08:00", close: "12:00", closed: true },
  },
  social: {
    facebook: "https://www.facebook.com/USA.MOTORCYCLE.CENTRE/",
    instagram: "https://www.instagram.com/usa.motorcycle.centre/",
    youtube: "",
    tiktok: "",
  },
  seo: {
    title: "U.S.A. Motorcycle Centre | Harley® Specialists · Albion Park Rail",
    description:
      "Harley-Davidson specialist workshop in Albion Park Rail. Servicing, smash repairs, tyres, parts, AMSOIL and U.S.A. rider clothing. Est. 1992. Call (02) 4257 2333.",
    keywords:
      "Harley Davidson service Illawarra, motorcycle repairs Albion Park Rail, USA Motorcycle Centre, Harley parts NSW, motorcycle tyres Wollongong",
  },
  homepage: {
    announcement:
      "Workshop open Mon–Fri 8am–5pm · Sat 8am–12pm · See Laurie or Mick · PH 4257 2333",
    heroKicker: "Est. 1992 · Albion Park Rail, NSW",
    heroTitle: "Servicing Harleys is our game.",
    heroSubtitle:
      "Independent Harley® specialist workshop for the Illawarra. Diagnostics, smash repairs, tyres, parts and genuine U.S.A. rider gear — from the same crew that’s been looking after your bike for more than three decades.",
    heroImage: "/workshop/chopper-build.jpg",
    heroCta: "Shop the range",
    heroSecondary: "Book a service",
  },
  shipping: {
    clickCollectEnabled: true,
    australiaPostEnabled: true,
    freeShippingThreshold: 150,
    flatRate: 14.95,
    clickCollectLabel: "Click & collect at 8 Miall Way",
  },
  tax: {
    gstRate: 0.1,
    pricesIncludeGst: true,
  },
  features: {
    shop: true,
    bookings: true,
    events: true,
    giftCards: true,
    newsletter: true,
    reviews: true,
  },
  stripe: {
    mode: "test",
    publishableKey: "",
    connected: false,
  },
};

export const products: Product[] = [
  {
    id: "p-hoodie-black",
    slug: "usa-mcc-flame-hoodie-black",
    name: "Flame Hoodie — Black",
    subtitle: "Shop hoodie · EST 1992 shield",
    description:
      "Heavyweight black hoodie with the U.S.A. Motorcycle Centre shield on the chest, EST 1992, full back print of the workshop crest and the original shop copy, plus flame sleeves finishing on the cuff badges. The piece the workshop wears.",
    price: 119,
    images: [
      "/products/hoodie-black-front.jpg",
      "/products/hoodie-black-back.jpg",
      "/products/sleeves-detail.jpg",
    ],
    category: "Apparel",
    tags: ["merch", "hoodie", "bestseller"],
    featured: true,
    inStock: true,
    brand: "U.S.A. MCC",
    variants: [
      { id: "s", label: "S", sku: "HOOD-BLK-S", stock: 8 },
      { id: "m", label: "M", sku: "HOOD-BLK-M", stock: 12 },
      { id: "l", label: "L", sku: "HOOD-BLK-L", stock: 14 },
      { id: "xl", label: "XL", sku: "HOOD-BLK-XL", stock: 10 },
      { id: "2xl", label: "2XL", sku: "HOOD-BLK-2XL", stock: 6 },
      { id: "3xl", label: "3XL", sku: "HOOD-BLK-3XL", stock: 4 },
    ],
    details: [
      "Front shield with EST 1992",
      "Full back workshop print and phone number",
      "Flame graphics down both sleeves",
      "Click & collect from Albion Park Rail",
    ],
  },
  {
    id: "p-crew-black",
    slug: "usa-mcc-flame-crew-black",
    name: "Flame Crew — Black",
    subtitle: "Shop crew · back print",
    description:
      "Black crew with the full U.S.A. Motorcycle Centre back print — shield, the original slogan, workshop services and PH 4257 2333 — over grey flame artwork. Sleeve flames and cuff badges.",
    price: 89,
    images: ["/products/crew-black-back.jpg", "/products/sleeves-detail.jpg"],
    category: "Apparel",
    tags: ["merch", "crew"],
    featured: true,
    inStock: true,
    brand: "U.S.A. MCC",
    variants: [
      { id: "s", label: "S", sku: "CREW-BLK-S", stock: 6 },
      { id: "m", label: "M", sku: "CREW-BLK-M", stock: 10 },
      { id: "l", label: "L", sku: "CREW-BLK-L", stock: 12 },
      { id: "xl", label: "XL", sku: "CREW-BLK-XL", stock: 8 },
      { id: "2xl", label: "2XL", sku: "CREW-BLK-2XL", stock: 5 },
      { id: "3xl", label: "3XL", sku: "CREW-BLK-3XL", stock: 3 },
    ],
  },
  {
    id: "p-crew-grey",
    slug: "usa-mcc-flame-crew-grey",
    name: "Flame Crew — Grey Marle",
    subtitle: "Shop crew · EST 1992",
    description:
      "Grey marle crew with the black U.S.A. Motorcycle Centre shield, EST 1992, flame sleeves and the full workshop back print. A weekday staple that still looks like it came out of the shop.",
    price: 89,
    images: [
      "/products/crew-grey-front.jpg",
      "/products/crew-grey-back.jpg",
      "/products/sleeves-detail.jpg",
    ],
    category: "Apparel",
    tags: ["merch", "crew"],
    featured: true,
    inStock: true,
    brand: "U.S.A. MCC",
    variants: [
      { id: "s", label: "S", sku: "CREW-GRY-S", stock: 7 },
      { id: "m", label: "M", sku: "CREW-GRY-M", stock: 11 },
      { id: "l", label: "L", sku: "CREW-GRY-L", stock: 13 },
      { id: "xl", label: "XL", sku: "CREW-GRY-XL", stock: 9 },
      { id: "2xl", label: "2XL", sku: "CREW-GRY-2XL", stock: 5 },
      { id: "3xl", label: "3XL", sku: "CREW-GRY-3XL", stock: 3 },
    ],
  },
  {
    id: "p-gift-100",
    slug: "workshop-gift-card-100",
    name: "Workshop Gift Card — $100",
    subtitle: "Redeem in-store or online",
    description:
      "A $100 U.S.A. Motorcycle Centre gift card. Good for apparel, parts, oils, tyres or put it toward a service. Printed in-store or emailed instantly at checkout.",
    price: 100,
    images: ["/brand/logo.png"],
    category: "Gift Cards",
    tags: ["gift"],
    featured: true,
    inStock: true,
    details: ["No expiry on store credit issued in-shop", "GST included"],
  },
  {
    id: "p-gift-50",
    slug: "workshop-gift-card-50",
    name: "Workshop Gift Card — $50",
    description:
      "A $50 U.S.A. Motorcycle Centre gift card for gear, oils or a contribution toward a service.",
    price: 50,
    images: ["/brand/logo.png"],
    category: "Gift Cards",
    tags: ["gift"],
    featured: false,
    inStock: true,
  },
  {
    id: "p-helmet",
    slug: "xrh-open-face-helmet",
    name: "Open Face Helmet",
    subtitle: "In-store fitting recommended",
    description:
      "Open-face lid from the range we keep on the wall. Come in and get fitted — we will not ship a helmet we have not confirmed is the right size. Click & collect from Albion Park Rail.",
    price: 189,
    images: ["/products/helmet-black.jpg"],
    category: "Helmets",
    tags: ["safety"],
    featured: true,
    inStock: true,
    brand: "XRH",
    variants: [
      { id: "s", label: "S", sku: "HLM-S", stock: 2 },
      { id: "m", label: "M", sku: "HLM-M", stock: 4 },
      { id: "l", label: "L", sku: "HLM-L", stock: 4 },
      { id: "xl", label: "XL", sku: "HLM-XL", stock: 3 },
    ],
    details: ["AS/NZS approved options in-store", "Fitting at 8 Miall Way"],
  },
  {
    id: "p-tyre-fit",
    slug: "tyre-fitment-voucher",
    name: "Tyre Supply & Fitment",
    subtitle: "Avon · Dunlop · Pirelli",
    description:
      "We stock and fit Avon, Dunlop and Pirelli. Price shown is a starting point for a quality cruiser tyre including electronic balancing — confirm size and compound with Laurie or Mick and we will lock in the exact figure.",
    price: 249,
    images: ["/workshop/pirelli-rack.jpg", "/workshop/dunlop-rack.jpg"],
    category: "Tyres",
    tags: ["workshop"],
    featured: true,
    inStock: true,
    details: [
      "Electronic wheel balancing included",
      "Alignment available",
      "Call (02) 4257 2333 with your size",
    ],
  },
  {
    id: "p-pirelli-nd",
    slug: "pirelli-night-dragon",
    name: "Pirelli Night Dragon",
    subtitle: "On the wall at Albion Park Rail",
    description:
      "Pirelli Night Dragon from the rack in the shop. Cruiser compound, fitted and electronically balanced here. Confirm size with Laurie or Mick — we will pull it off the wall.",
    price: 269,
    images: ["/workshop/pirelli-rack.jpg"],
    category: "Tyres",
    tags: ["pirelli", "workshop"],
    featured: true,
    inStock: true,
    brand: "Pirelli",
    details: ["Fitted in-house", "Electronic balancing included"],
  },
  {
    id: "p-dunlop",
    slug: "dunlop-cruiser-tyres",
    name: "Dunlop Cruiser Tyres",
    subtitle: "D402 · D427 and the touring sizes we keep",
    description:
      "Dunlop cruiser and touring rubber from the blue racks. We stock the sizes that actually fit Harleys around the Illawarra. Price is a starting point — call with the size on the sidewall.",
    price: 239,
    images: ["/workshop/dunlop-rack.jpg"],
    category: "Tyres",
    tags: ["dunlop", "workshop"],
    featured: true,
    inStock: true,
    brand: "Dunlop",
    details: ["Fitted in-house", "Electronic balancing included"],
  },
  {
    id: "p-amsoil",
    slug: "amsoil-v-twin-oil-change-kit",
    name: "V-Twin Oil Change Kit",
    subtitle: "Authorised AMSOIL reseller",
    description:
      "AMSOIL V-Twin engine and transmission lubricants plus a matching filter. We are an authorised AMSOIL reseller — buy the kit and fit it yourself, or book it in and we will do the change on the lift.",
    price: 129,
    images: ["/products/oils.jpg"],
    category: "Oils & Fluids",
    tags: ["amsoil", "service"],
    featured: true,
    inStock: true,
    brand: "AMSOIL",
    details: ["V-Twin engine oil", "Transmission lubricant", "Oil filter"],
  },
  {
    id: "p-penrite",
    slug: "penrite-v-twin-oil",
    name: "Penrite V-Twin Oil 4L",
    description:
      "Penrite V-Twin from the rack we have always kept. Tell us the year and model and we will pick the right grade.",
    price: 64,
    images: ["/products/oils.jpg"],
    category: "Oils & Fluids",
    tags: ["penrite"],
    featured: false,
    inStock: true,
    brand: "Penrite",
  },
  {
    id: "p-battery",
    slug: "motorcycle-battery-fitment",
    name: "Motorcycle Battery + Fitment",
    subtitle: "In-store programming where required",
    description:
      "Quality motorcycle battery sized to your bike, plus fitment. Bring the bike in — we will test the charging system while it is on the bench.",
    price: 149,
    images: ["/workshop/clutch-job.jpg"],
    category: "Electrical",
    tags: ["electrical"],
    featured: false,
    inStock: true,
  },
  {
    id: "p-apes",
    slug: "ape-hanger-handlebar-kit",
    name: "Ape Hanger Handlebar Kit",
    subtitle: "Ask Laurie about Burleigh bars",
    description:
      "Ape hangers, risers and the lines to match. We have fitted 16\" highballs on Sportsters and Burleigh apes on everything from Softails to baggers. Kit price is a starting point — we quote the full job including cables and brake lines.",
    price: 489,
    images: ["/workshop/chopper-build.jpg", "/workshop/primary-case.jpg"],
    category: "Parts & Accessories",
    tags: ["handlebars", "custom"],
    featured: true,
    inStock: true,
    details: ["Bars, risers and hardware", "Cables and lines quoted to the bike"],
  },
  {
    id: "p-kuryakyn",
    slug: "kuryakyn-chrome-accent-kit",
    name: "Chrome Accent Kit",
    subtitle: "Kuryakyn · Arlen Ness",
    description:
      "Chrome covers, pegs and accents from the brands we have stocked for decades — Kuryakyn, Arlen Ness and Accel. Tell us the model and we will pull the right pieces.",
    price: 179,
    images: ["/workshop/chopper-build.jpg"],
    category: "Parts & Accessories",
    tags: ["chrome", "kuryakyn"],
    featured: false,
    inStock: true,
    brand: "Kuryakyn",
  },
];

export const services: Service[] = [
  {
    id: "s-harley",
    slug: "harley-service-tuning",
    name: "Harley® Service & Tuning",
    summary: "Logbook services, diagnostics and dyno-style tuning on V-Twins.",
    description:
      "If it is not firing the way it used to, we have computerised diagnostic and tuning equipment that will get to the root of it. Laurie and Mick have been looking after Harleys in the Illawarra since 1992 — scheduled services, cam jobs, carb and EFI work, and the unglamorous stuff that keeps you on the road.",
    duration: "Half to full day",
    fromPrice: 249,
    image: "/workshop/primary-case.jpg",
  },
  {
    id: "s-smash",
    slug: "smash-repairs-insurance",
    name: "Smash Repairs & Insurance",
    summary: "Insurance work and crash repairs, quoted properly.",
    description:
      "Fairings, guards, wheels, bars and the hidden damage that shows up after a drop. We work with insurers and we work with riders who would rather keep it cash. Bring photos or ride it in.",
    duration: "Quoted",
    image: "/workshop/chopper-build.jpg",
  },
  {
    id: "s-tyres",
    slug: "tyres-alignment-balancing",
    name: "Tyres, Alignment & Balancing",
    summary: "Avon, Dunlop and Pirelli — fitted, aligned and electronically balanced.",
    description:
      "Motorcycle tyre fitting, electronic wheel balancing and alignment. We keep the compounds that work on cruisers and tourers, and we will tell you if a cheaper tyre is a false economy.",
    duration: "1–2 hours",
    fromPrice: 40,
    image: "/workshop/pirelli-rack.jpg",
  },
  {
    id: "s-electrical",
    slug: "electrical-repairs-wiring",
    name: "Electrical Repairs & Wiring",
    summary: "Charging, lighting, aftermarket wiring and the gremlins in between.",
    description:
      "Batteries, regulators, looms, aftermarket lights and the wiring that never quite got finished. We diagnose first — then we fix it so it stays fixed.",
    duration: "Quoted",
    image: "/workshop/clutch-job.jpg",
  },
  {
    id: "s-custom",
    slug: "customising",
    name: "Customising",
    summary: "Bars, pipes, intake, seats, lighting — built to the bike you actually ride.",
    description:
      "Our mechanics can take on customising work: ape hangers, exhaust, air cleaners, seats and the small chrome that changes how a bike sits. We will tell you what is worth doing.",
    duration: "Quoted",
    image: "/workshop/chopper-build.jpg",
  },
  {
    id: "s-diag",
    slug: "diagnostics",
    name: "Computerised Diagnostics",
    summary: "Find the fault before you throw parts at it.",
    description:
      "Computerised diagnostic and tuning equipment for Harley-Davidson and a wide range of road bikes. Book a diagnosis if it is intermittent, in limp mode, or just not right.",
    duration: "1–3 hours",
    fromPrice: 99,
    image: "/workshop/primary-case.jpg",
  },
];

export const events: EventItem[] = [
  {
    id: "e-b4h-ball",
    slug: "bikers-4-heroes-masquerade-ball-2026",
    title: "Bikers 4 Heroes Masquerade Ball",
    summary:
      "A night out for the Illawarra riding community, raising money for the i98FM Illawarra Convoy.",
    description:
      "U.S.A. Motorcycle Centre is behind the local riding community — including Bikers 4 Heroes. Gather your friends and family for an evening of dancing and a good cause at City Beach Function Centre, Wollongong. Tickets through Bikers 4 Heroes.",
    date: "2026-09-26",
    time: "6:00 pm",
    location: "City Beach Function Centre, Marine Drive, Wollongong",
    image: "/workshop/chopper-build.jpg",
    ticketed: true,
    featured: true,
    price: 0,
  },
  {
    id: "e-saturday",
    slug: "saturday-workshop-morning",
    title: "Saturday Workshop Morning",
    summary: "Coffee, a yarn and the parts wall — 8am to midday.",
    description:
      "We open Saturday mornings for parts, apparel, oil and a look at whatever you rode in on. No booking needed for a chat. Book if you want it on the lift.",
    date: "2026-10-11",
    time: "8:00 am – 12:00 pm",
    location: "8 Miall Way, Albion Park Rail",
    image: "/workshop/dunlop-rack.jpg",
    ticketed: false,
    featured: true,
  },
  {
    id: "e-spring",
    slug: "spring-service-month",
    title: "Spring Service Month",
    summary: "Get the Harley ready before the summer runs start stacking up.",
    description:
      "Book a major or minor service through October and we will include a charging-system check and a tyre inspection. Mention Spring Service Month when you call.",
    date: "2026-10-01",
    time: "All month",
    location: "U.S.A. Motorcycle Centre workshop",
    image: "/workshop/primary-case.jpg",
    ticketed: false,
    featured: true,
  },
  {
    id: "e-illawarra-night",
    slug: "illawarra-harley-catch-up",
    title: "Illawarra Harley Catch-up",
    summary: "Park up, talk rubbish, look at bars and pipes.",
    description:
      "An informal catch-up for Harley riders around the Illawarra. Details posted on Facebook — follow U.S.A. Motorcycle Centre for the next date. The workshop is the usual meeting point.",
    date: "2026-11-07",
    time: "From 4:00 pm",
    location: "8 Miall Way, Albion Park Rail",
    image: "/workshop/clutch-job.jpg",
    ticketed: false,
    featured: false,
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    name: "Tony Hair",
    quote:
      "Laurie and Mick went above and beyond to install my 16\" highballs on my 883 Sporty. Their work is second to none — outstanding. If there were more than 5 stars it would be a 10.",
    rating: 5,
    source: "Local search",
  },
  {
    id: "r2",
    name: "Dale Gibbons",
    quote:
      "I needed a Ventura rack in a big hurry for a last-minute trip. Laurie worked his magic and the rack was here in less than two days.",
    rating: 5,
    source: "Local search",
  },
  {
    id: "r3",
    name: "Brendan S.",
    quote:
      "Got new Black Burleigh apes and risers from the guys at USA Cycles. Went above and beyond. Perfect knowledge and advice for my Harley — made it look tough as.",
    rating: 5,
    source: "Yellow Pages",
  },
  {
    id: "r4",
    name: "Deon",
    quote: "Great service and advice always.",
    rating: 5,
    source: "Local search",
  },
  {
    id: "r5",
    name: "Reg Potter",
    quote: "Great service and good advice.",
    rating: 5,
    source: "Chamber listing",
  },
];

export const brands = [
  "Harley-Davidson",
  "AMSOIL",
  "Penrite",
  "Avon",
  "Dunlop",
  "Pirelli",
  "Kuryakyn",
  "Arlen Ness",
  "Accel",
  "XRH",
];

export const discounts: Discount[] = [
  {
    id: "d-welcome",
    code: "ILLAWARRA10",
    type: "percent",
    value: 10,
    active: true,
    minSpend: 80,
  },
];

export const categories = [
  "Apparel",
  "Helmets",
  "Tyres",
  "Oils & Fluids",
  "Electrical",
  "Parts & Accessories",
  "Gift Cards",
];
